### PR TITLE
Prepare for publishing to NPM

### PR DESCRIPTION
**Pull request by spikebrehm**
This PR is one step in addressing tildeio/router.js#69

~~It depends on https://github.com/tildeio/route-recognizer/pull/16; once this is merged in, I'll update the ref in package.json to point to the NPM module instead of the git repo.~~
- Update `package.json`:
  - Add `main` field, pointing to CommonJS build at `dist/commonjs/main.js`.
  - Add `route-recognizer` and `rsvp` as dependencies.
  - Change `name` field from `router` to `router.js`, which is unique in NPM and allows using Browserify with `require('router.js');`.
- Add `.npmignore`, ignoring build tasks.

### CODE REVIEW

**Comment by cheapsteak** [comment]
Can't get this branch or master working with browserify. Burnt 10 hours :(  
Anyone have any advice on how to get this working?

**Comment by pzuraq** [comment]
@cheapsteak I've figured out the problems, I'm going to create a new PR to keep everything clean. Will push pushing in the next hour or so.

**Comment by benjamindulau** [comment]
Any update on this? I'd really like to use this router in a CommonJS (or ES6) environment ;-)

**Comment by pzuraq** [comment]
@benjamindulau I attempted to make a PR a while back but there was some issue with the shims that prevented it from being imported properly. If you checkout #149 it is (or was at least) 99% working, just has that one problem.

**Comment by kruppel** [comment]
> @benjamindulau I attempted to make a PR a while back but there was some issue with the shims that prevented it from being imported properly. If you checkout #149 it is (or was at least) 99% working, just has that one problem.

@pzuraq Took a pass at resolving your issue, kruppel/router.js@038b2538ca56b2e85e8ca5b07346b0448597463b . Rather than build cjs modules, I made changes to create a UMD dist, which can be loaded in a node environment. In terms of properly loading the route-recognizer dependency, a switch over to [ember-cli/broccoli-es6modules](https://github.com/ember-cli/broccoli-es6modules) seemed to do the trick (see [esperanto's docs on strict mode](https://github.com/esperantojs/esperanto/wiki/Strict-mode) for more context). The only caveat is that access to the `Router` constructor is through `default`, i.e. `var Router = require('router').default`.

**Comment by mrself** [comment]
Was this isssue resolved?

**Comment by nathanhammond** [comment]
We're publishing to npm as of 1.2.4: https://www.npmjs.com/package/router_js

**Pull request closed without merging**
